'use client';

import HeroSection from '@/components/HeroSection';
import Navbar from '@/components/Navbar';
import { ChakraProvider } from '@chakra-ui/react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><ChakraProvider>
        <Navbar />
        {children}
      </ChakraProvider></body>
    </html>
  )
}
